### ISSUE TITLE
Error in Execution of Make command on Postgre Sql V 14

### ISSUE THREAD

**Issue by dpanjwani06** [pg-fdw/db2_fdw#33]
Hi,

When trying to run the make command , I am getting the below error

**-bash-4.2$ make install
gcc -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fPIC -g -fPIC -I/opt/KX/IBM/db2/insthome1/sqllib/include -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o db2_fdw.o db2_fdw.c
db2_fdw.c: In function db2_fdw_handler:
db2_fdw.c:366:39: warning: assignment from incompatible pointer type [enabled by default]
   fdwroutine->AddForeignUpdateTargets = db2AddForeignUpdateTargets;
                                       ^
db2_fdw.c: In function "db2BeginForeignModify":
db2_fdw.c:1628:26: error: "ModifyTableState" has no member named "mt_plans"
   Plan *subplan = mtstate->mt_plans[subplan_index]->plan;
                          ^
make: *** [db2_fdw.o] Error 1**

Can someone please let me know if I have missed any steps for installing db2_fdw extension for Db2 on RHEL 7?

Thanks,
Dhiraj Panjwani

**Comment by devrimgunduz** [comment]
Hi @wolfgangbrandl ,

Any updates for PG 13 and 14 support? 

Thanks!

**Comment by omensinger** [comment]
It works with PG 13.2 and DB2 v11.5.4.0 out of the box. But I get the same error message (see above) with PG 14.3.

**Comment by wolfgangbrandl** [comment]
I will make the upgrade in July August.

 

From: Devrim Gündüz ***@***.***>
Reply to: wolfgangbrandl/db2_fdw ***@***.***>
Date: Monday, 30. May 2022 at 21:48
To: wolfgangbrandl/db2_fdw ***@***.***>
Cc: Wolfgang Brandl ***@***.***>, Mention ***@***.***>
Subject: Re: [wolfgangbrandl/db2_fdw] Error in Execution of Make command on Postgre Sql V 14 (Issue #33)

 

Hi @wolfgangbrandl ,

Any updates for PG 13 and 14 support?

Thanks!

**Comment by nileger** [comment]
Hi, any updates on this issue? I experience the same error for PostgreSQL 14.3

**Comment by wolfgangbrandl** [comment]
I have upgraded to Version 14

**Comment by wolfgangbrandl** [comment]
> Hi, any updates on this issue? I experience the same error for PostgreSQL 14.3

I have upgraded to Version 14

**Comment by devrimgunduz-edb** [comment]
Thanks a lot @wolfgangbrandl ! I built and pushed packages.
